(title = "⚒️ Moderation Commands", description = " ")
    em.add_field(name = "!clear (optional amount)", value = "Clears messages in a particular channel.\n*Required Permission: Manage Messages*")
    em.add_field(name = "!mute [member] (optional reason)", value = "Mutes a specific member.\n*Required Permission: Manage Messages*")
    em.add_field(name = "!unmute [member]", value = "Unmuted a member.\n*Required Permission: Manage Messages*")
    em.add_field(name = "!kick [member] (optional reason)", value = "Kicks a member from the server.\n*Required Permission: Kick Members*")
    em.add_field(name = "!ban [member] (optional reason)", value = "Bans a member from the server.\n*Required Permission: Ban Members*")
    em.add_field(name = "!unban [member]", value = "Unbans a member from a the server.\n*Required Permission: Ban Members*")
    em.add_field(name = "!addrole [member] [role]", value = "Adds a role to a member.\n*Required Permission: Manage Roles*")
    em.add_field(name = "!delrole [member] [role]", value = "Removes a role from a member.\n*Required Permission: Manage Roles*")
    ctx.say(embed = em)
